### ISSUE TITLE
using associations

### ISSUE THREAD

**Issue by angelxmoreno** [chunksnbits/store.pouchdb#1]
in the readme the examples has

```
Playlists.hasMany('tracks');
```

In this example, what is the string `tracks` ? is it the name of the store? So for instance:

``` js
var Playlists = new PouchDb('playlist').store();
var Tracks = new PouchDb('track').store();
Playlists.hasMany('tracks');
Tracks.hasOne('playlist');
```

Is this the right setup ?

**Comment by chunksnbits** [comment]
The store would have to be named exactly by the name you are refering to, e.g., 

```
var Tracks = new PouchDb('tracks').store();
```

But you could also pass the related model directly, like: 

```
Playlists.hasMany(Tracks);
```

which in case both are available in the same context should be the more convenient way.

**Comment by angelxmoreno** [comment]
thanks @chunksnbits I get it now. I am passing either the name of the db as a string or an instance of the db as an object. So basically given:

```
var db1name = 'tracks123';
var Tracks = new PouchDb(db1name).store();

var db2name = 'playlists456';
var Playlists = new PouchDb(db2name).store();
```

these 2 are the same thing:

``` js
Playlists.hasMany(Tracks); //passing PouchDb instance
Playlists.hasMany(db1name); //passing string of db name
```

correct?

**Comment by angelxmoreno** [comment]
shame on me, did not read that far down: 

```
The store argument can be be either as string with the name of the store or store instance.
```
